// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	HealthCheckRequest
	HealthCheckResponse
	SubmitTransactionRequest
	SubmitTransactionResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionStatusEnum int32

const (
	TransactionStatusEnum_REJECTED  TransactionStatusEnum = 0
	TransactionStatusEnum_ACCEPTED  TransactionStatusEnum = 1
	TransactionStatusEnum_CONFIRMED TransactionStatusEnum = 2
)

var TransactionStatusEnum_name = map[int32]string{
	0: "REJECTED",
	1: "ACCEPTED",
	2: "CONFIRMED",
}
var TransactionStatusEnum_value = map[string]int32{
	"REJECTED":  0,
	"ACCEPTED":  1,
	"CONFIRMED": 2,
}

func (x TransactionStatusEnum) String() string {
	return proto.EnumName(TransactionStatusEnum_name, int32(x))
}
func (TransactionStatusEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HealthCheckRequest struct {
}

func (m *HealthCheckRequest) Reset()                    { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()               {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HealthCheckResponse struct {
}

func (m *HealthCheckResponse) Reset()                    { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()               {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SubmitTransactionRequest struct {
	// transaction data in pb format
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	// digital signature of the data signed by
	// the source account private key
	Signature string `protobuf:"bytes,2,opt,name=Signature" json:"Signature,omitempty"`
}

func (m *SubmitTransactionRequest) Reset()                    { *m = SubmitTransactionRequest{} }
func (m *SubmitTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*SubmitTransactionRequest) ProtoMessage()               {}
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SubmitTransactionRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SubmitTransactionRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type SubmitTransactionResponse struct {
	TransactionStatus TransactionStatusEnum `protobuf:"varint,1,opt,name=TransactionStatus,enum=rpc.TransactionStatusEnum" json:"TransactionStatus,omitempty"`
	// the transaction hash is only valid when the response
	// status is ACCEPTED or CONFIRMED
	TransactionHash string `protobuf:"bytes,2,opt,name=TransactionHash" json:"TransactionHash,omitempty"`
	// error message for REJECTED transaction
	ErrorMessage string `protobuf:"bytes,3,opt,name=ErrorMessage" json:"ErrorMessage,omitempty"`
}

func (m *SubmitTransactionResponse) Reset()                    { *m = SubmitTransactionResponse{} }
func (m *SubmitTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*SubmitTransactionResponse) ProtoMessage()               {}
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SubmitTransactionResponse) GetTransactionStatus() TransactionStatusEnum {
	if m != nil {
		return m.TransactionStatus
	}
	return TransactionStatusEnum_REJECTED
}

func (m *SubmitTransactionResponse) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func (m *SubmitTransactionResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthCheckRequest)(nil), "rpc.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "rpc.HealthCheckResponse")
	proto.RegisterType((*SubmitTransactionRequest)(nil), "rpc.SubmitTransactionRequest")
	proto.RegisterType((*SubmitTransactionResponse)(nil), "rpc.SubmitTransactionResponse")
	proto.RegisterEnum("rpc.TransactionStatusEnum", TransactionStatusEnum_name, TransactionStatusEnum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ULTNode service

type ULTNodeClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error)
}

type uLTNodeClient struct {
	cc *grpc.ClientConn
}

func NewULTNodeClient(cc *grpc.ClientConn) ULTNodeClient {
	return &uLTNodeClient{cc}
}

func (c *uLTNodeClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/rpc.ULTNode/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uLTNodeClient) SubmitTransaction(ctx context.Context, in *SubmitTransactionRequest, opts ...grpc.CallOption) (*SubmitTransactionResponse, error) {
	out := new(SubmitTransactionResponse)
	err := grpc.Invoke(ctx, "/rpc.ULTNode/SubmitTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ULTNode service

type ULTNodeServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	SubmitTransaction(context.Context, *SubmitTransactionRequest) (*SubmitTransactionResponse, error)
}

func RegisterULTNodeServer(s *grpc.Server, srv ULTNodeServer) {
	s.RegisterService(&_ULTNode_serviceDesc, srv)
}

func _ULTNode_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ULTNodeServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ULTNode/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ULTNodeServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ULTNode_SubmitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ULTNodeServer).SubmitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ULTNode/SubmitTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ULTNodeServer).SubmitTransaction(ctx, req.(*SubmitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ULTNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.ULTNode",
	HandlerType: (*ULTNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _ULTNode_HealthCheck_Handler,
		},
		{
			MethodName: "SubmitTransaction",
			Handler:    _ULTNode_SubmitTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xd1, 0x4e, 0xfa, 0x30,
	0x14, 0xc6, 0x29, 0xfc, 0xf3, 0x57, 0x8e, 0xa0, 0x70, 0x94, 0x38, 0x89, 0x1a, 0xb2, 0x2b, 0xe2,
	0x05, 0x17, 0xf8, 0x04, 0x32, 0x6a, 0xd0, 0x00, 0x9a, 0x6e, 0x3e, 0x40, 0x99, 0x0d, 0x5b, 0x94,
	0x75, 0xb6, 0x9d, 0x2f, 0xe4, 0x23, 0xf8, 0x82, 0x86, 0x3a, 0xe3, 0x70, 0x70, 0xb7, 0xf3, 0x3b,
	0xfb, 0xbe, 0xd3, 0x9e, 0xaf, 0xd0, 0xd4, 0x42, 0xbd, 0xc7, 0xa1, 0x18, 0xa4, 0x4a, 0x1a, 0x89,
	0x35, 0x95, 0x86, 0xee, 0x09, 0xe0, 0x44, 0xf0, 0x57, 0x13, 0x79, 0x91, 0x08, 0x5f, 0x98, 0x78,
	0xcb, 0x84, 0x36, 0x6e, 0x07, 0x8e, 0x37, 0xa8, 0x4e, 0x65, 0xa2, 0x85, 0x3b, 0x05, 0xc7, 0xcf,
	0x16, 0xab, 0xd8, 0x04, 0x8a, 0x27, 0x9a, 0x87, 0x26, 0x96, 0x49, 0x2e, 0x41, 0x84, 0x7f, 0x63,
	0x6e, 0xb8, 0x43, 0x7a, 0xa4, 0xdf, 0x60, 0xf6, 0x1b, 0xcf, 0xa1, 0xee, 0xc7, 0xcb, 0x84, 0x9b,
	0x4c, 0x09, 0xa7, 0xda, 0x23, 0xfd, 0x3a, 0xfb, 0x05, 0xee, 0x27, 0x81, 0xb3, 0x2d, 0x76, 0xdf,
	0xb3, 0x70, 0x02, 0xed, 0x02, 0xf6, 0x0d, 0x37, 0x99, 0xb6, 0xe6, 0x87, 0xc3, 0xee, 0x40, 0xa5,
	0xe1, 0xa0, 0xd4, 0xa5, 0x49, 0xb6, 0x62, 0x65, 0x11, 0xf6, 0xe1, 0xa8, 0x00, 0x27, 0x5c, 0x47,
	0xf9, 0x59, 0xfe, 0x62, 0x74, 0xa1, 0x41, 0x95, 0x92, 0x6a, 0x26, 0xb4, 0xe6, 0x4b, 0xe1, 0xd4,
	0xec, 0x6f, 0x1b, 0xec, 0x6a, 0x04, 0x9d, 0xad, 0x93, 0xb1, 0x01, 0xfb, 0x8c, 0xde, 0x53, 0x2f,
	0xa0, 0xe3, 0x56, 0x65, 0x5d, 0xdd, 0x78, 0x1e, 0x7d, 0x5c, 0x57, 0x04, 0x9b, 0x50, 0xf7, 0x1e,
	0xe6, 0xb7, 0x77, 0x6c, 0x46, 0xc7, 0xad, 0xea, 0xf0, 0x83, 0xc0, 0xde, 0xd3, 0x34, 0x98, 0xcb,
	0x67, 0x81, 0x23, 0x38, 0x28, 0xac, 0x1a, 0x4f, 0xed, 0xdd, 0xca, 0x91, 0x74, 0x9d, 0x72, 0x23,
	0x4f, 0xa5, 0x82, 0x01, 0xb4, 0x4b, 0x8b, 0xc4, 0x0b, 0x2b, 0xd8, 0x95, 0x57, 0xf7, 0x72, 0x57,
	0xfb, 0xc7, 0x75, 0xf1, 0xdf, 0x3e, 0x93, 0xeb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0xa6,
	0x9d, 0x72, 0x37, 0x02, 0x00, 0x00,
}
