// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
	SubmitTxRequest
	SubmitTxResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxStatusEnum int32

const (
	TxStatusEnum_REJECTED  TxStatusEnum = 0
	TxStatusEnum_ACCEPTED  TxStatusEnum = 1
	TxStatusEnum_CONFIRMED TxStatusEnum = 2
	TxStatusEnum_FAILED    TxStatusEnum = 3
)

var TxStatusEnum_name = map[int32]string{
	0: "REJECTED",
	1: "ACCEPTED",
	2: "CONFIRMED",
	3: "FAILED",
}
var TxStatusEnum_value = map[string]int32{
	"REJECTED":  0,
	"ACCEPTED":  1,
	"CONFIRMED": 2,
	"FAILED":    3,
}

func (x TxStatusEnum) String() string {
	return proto.EnumName(TxStatusEnum_name, int32(x))
}
func (TxStatusEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HelloRequest struct {
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HelloResponse struct {
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SubmitTxRequest struct {
	// transaction data in pb format
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	// digital signature of the data signed by
	// the source account private key
	Signature string `protobuf:"bytes,2,opt,name=Signature" json:"Signature,omitempty"`
}

func (m *SubmitTxRequest) Reset()                    { *m = SubmitTxRequest{} }
func (m *SubmitTxRequest) String() string            { return proto.CompactTextString(m) }
func (*SubmitTxRequest) ProtoMessage()               {}
func (*SubmitTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SubmitTxRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SubmitTxRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type SubmitTxResponse struct {
	TxStatus TxStatusEnum `protobuf:"varint,1,opt,name=TxStatus,enum=rpc.TxStatusEnum" json:"TxStatus,omitempty"`
	// the transaction hash is only valid when the response
	// status is ACCEPTED or CONFIRMED
	TxHash string `protobuf:"bytes,2,opt,name=TxHash" json:"TxHash,omitempty"`
	// error message for REJECTED transaction
	ErrorMessage string `protobuf:"bytes,3,opt,name=ErrorMessage" json:"ErrorMessage,omitempty"`
}

func (m *SubmitTxResponse) Reset()                    { *m = SubmitTxResponse{} }
func (m *SubmitTxResponse) String() string            { return proto.CompactTextString(m) }
func (*SubmitTxResponse) ProtoMessage()               {}
func (*SubmitTxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SubmitTxResponse) GetTxStatus() TxStatusEnum {
	if m != nil {
		return m.TxStatus
	}
	return TxStatusEnum_REJECTED
}

func (m *SubmitTxResponse) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *SubmitTxResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "rpc.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "rpc.HelloResponse")
	proto.RegisterType((*SubmitTxRequest)(nil), "rpc.SubmitTxRequest")
	proto.RegisterType((*SubmitTxResponse)(nil), "rpc.SubmitTxResponse")
	proto.RegisterEnum("rpc.TxStatusEnum", TxStatusEnum_name, TxStatusEnum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	SubmitTx(ctx context.Context, in *SubmitTxRequest, opts ...grpc.CallOption) (*SubmitTxResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/rpc.Node/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) SubmitTx(ctx context.Context, in *SubmitTxRequest, opts ...grpc.CallOption) (*SubmitTxResponse, error) {
	out := new(SubmitTxResponse)
	err := grpc.Invoke(ctx, "/rpc.Node/SubmitTx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	SubmitTx(context.Context, *SubmitTxRequest) (*SubmitTxResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Node/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_SubmitTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SubmitTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Node/SubmitTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SubmitTx(ctx, req.(*SubmitTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Node_Hello_Handler,
		},
		{
			MethodName: "SubmitTx",
			Handler:    _Node_SubmitTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x51, 0x6b, 0xf2, 0x30,
	0x14, 0x86, 0xad, 0xfa, 0x89, 0x1e, 0xaa, 0xf6, 0x3b, 0x6c, 0x43, 0x64, 0x17, 0xd2, 0x2b, 0x19,
	0xac, 0x0c, 0x77, 0xb5, 0x4b, 0x69, 0x23, 0x3a, 0xa6, 0x1b, 0x69, 0xff, 0x40, 0xec, 0x82, 0x2b,
	0x68, 0xd3, 0x25, 0xe9, 0xe8, 0xcd, 0xfe, 0xfb, 0x30, 0xb6, 0xb3, 0xf3, 0x2e, 0xef, 0x93, 0x93,
	0x87, 0xe4, 0x0d, 0xf4, 0x15, 0x97, 0x5f, 0x49, 0xcc, 0xbd, 0x4c, 0x0a, 0x2d, 0xb0, 0x25, 0xb3,
	0xd8, 0x1d, 0x80, 0xbd, 0xe4, 0xfb, 0xbd, 0xa0, 0xfc, 0x33, 0xe7, 0x4a, 0xbb, 0x43, 0xe8, 0x97,
	0x59, 0x65, 0x22, 0x55, 0xdc, 0xf5, 0x61, 0x18, 0xe6, 0xdb, 0x43, 0xa2, 0xa3, 0xa2, 0x9c, 0x41,
	0x84, 0x76, 0xc0, 0x34, 0x1b, 0x59, 0x13, 0x6b, 0x6a, 0x53, 0xb3, 0xc6, 0x5b, 0xe8, 0x85, 0xc9,
	0x2e, 0x65, 0x3a, 0x97, 0x7c, 0xd4, 0x9c, 0x58, 0xd3, 0x1e, 0x3d, 0x03, 0xf7, 0x1b, 0x9c, 0xb3,
	0xe4, 0x24, 0xc6, 0x7b, 0xe8, 0x46, 0x45, 0xa8, 0x99, 0xce, 0x95, 0x31, 0x0d, 0x66, 0xff, 0x3d,
	0x99, 0xc5, 0x5e, 0x05, 0x49, 0x9a, 0x1f, 0xe8, 0xef, 0x08, 0xde, 0x40, 0x27, 0x2a, 0x96, 0x4c,
	0x7d, 0x94, 0xf6, 0x32, 0xa1, 0x0b, 0x36, 0x91, 0x52, 0xc8, 0x35, 0x57, 0x8a, 0xed, 0xf8, 0xa8,
	0x65, 0x76, 0xff, 0xb0, 0x3b, 0x02, 0x76, 0xdd, 0x8a, 0x36, 0x74, 0x29, 0x79, 0x26, 0x7e, 0x44,
	0x02, 0xa7, 0x71, 0x4c, 0x73, 0xdf, 0x27, 0x6f, 0xc7, 0x64, 0x61, 0x1f, 0x7a, 0xfe, 0xeb, 0x66,
	0xb1, 0xa2, 0x6b, 0x12, 0x38, 0x4d, 0x04, 0xe8, 0x2c, 0xe6, 0xab, 0x17, 0x12, 0x38, 0xad, 0x99,
	0x82, 0xf6, 0x46, 0xbc, 0x73, 0x7c, 0x80, 0x7f, 0xa6, 0x23, 0x3c, 0x5d, 0xb8, 0xde, 0xdf, 0x18,
	0xeb, 0xa8, 0xac, 0xb0, 0x81, 0x4f, 0xd0, 0xad, 0xde, 0x8f, 0x57, 0x66, 0xe2, 0xa2, 0xd3, 0xf1,
	0xf5, 0x05, 0xad, 0x8e, 0x6e, 0x3b, 0xe6, 0xb3, 0x1e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x20,
	0x02, 0x28, 0x9b, 0xbd, 0x01, 0x00, 0x00,
}
