// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package ultpb is a generated protocol buffer package.

It is generated from these files:
	account.proto
	asset.proto
	consensus.proto
	ledger.proto
	transaction.proto

It has these top-level messages:
	Account
	Asset
	ConsensusValue
	Quorum
	Nominate
	Ballot
	Prepare
	Confirm
	Externalize
	Statement
	LedgerHeader
	Ledger
	Op
	Tx
	TxSet
	CreateAccountOp
	PaymentOp
	PathPaymentOp
	TrustOp
*/
package ultpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	// public key of this account
	AccountID string `protobuf:"bytes,1,opt,name=AccountID" json:"AccountID,omitempty"`
	// balance in ULUs
	Balance uint64 `protobuf:"varint,2,opt,name=Balance" json:"Balance,omitempty"`
	// public key of the signer of this account
	Signer string `protobuf:"bytes,3,opt,name=Signer" json:"Signer,omitempty"`
	// latest transaction sequence number
	SequenceNumber uint64 `protobuf:"varint,4,opt,name=SequenceNumber" json:"SequenceNumber,omitempty"`
	// number of entries belong to this account
	EntryCount uint32 `protobuf:"varint,5,opt,name=EntryCount" json:"EntryCount,omitempty"`
	// ULTkeys of transactions belongs to this account
	TxKeyList []string `protobuf:"bytes,6,rep,name=TxKeyList" json:"TxKeyList,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Account) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *Account) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Account) GetEntryCount() uint32 {
	if m != nil {
		return m.EntryCount
	}
	return 0
}

func (m *Account) GetTxKeyList() []string {
	if m != nil {
		return m.TxKeyList
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "ultpb.Account")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xcd, 0x29, 0x29, 0x48,
	0x52, 0xda, 0xcf, 0xc8, 0xc5, 0xee, 0x08, 0x91, 0x10, 0x92, 0xe1, 0xe2, 0x84, 0x32, 0x3d, 0x5d,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x12, 0x5c, 0xec, 0x4e, 0x89, 0x39,
	0x89, 0x79, 0xc9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x30, 0xae, 0x90, 0x18, 0x17,
	0x5b, 0x70, 0x66, 0x7a, 0x5e, 0x6a, 0x91, 0x04, 0x33, 0x58, 0x13, 0x94, 0x27, 0xa4, 0xc6, 0xc5,
	0x17, 0x9c, 0x5a, 0x58, 0x9a, 0x9a, 0x97, 0x9c, 0xea, 0x57, 0x9a, 0x9b, 0x94, 0x5a, 0x24, 0xc1,
	0x02, 0xd6, 0x88, 0x26, 0x2a, 0x24, 0xc7, 0xc5, 0xe5, 0x9a, 0x57, 0x52, 0x54, 0xe9, 0x0c, 0xb2,
	0x49, 0x82, 0x55, 0x81, 0x51, 0x83, 0x37, 0x08, 0x49, 0x04, 0xe4, 0xae, 0x90, 0x0a, 0xef, 0xd4,
	0x4a, 0x9f, 0xcc, 0xe2, 0x12, 0x09, 0x36, 0x05, 0x66, 0x90, 0xbb, 0xe0, 0x02, 0x49, 0x6c, 0x60,
	0xff, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x89, 0xad, 0xfb, 0x31, 0xe0, 0x00, 0x00, 0x00,
}
