// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package ultpb is a generated protocol buffer package.

It is generated from these files:
	account.proto
	asset.proto
	ledger.proto
	transaction.proto

It has these top-level messages:
	Account
	Asset
	LedgerHeader
	Op
	Tx
	TxList
	CreateAccountOp
	PaymentOp
*/
package ultpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	// public key of this account
	AccountID string `protobuf:"bytes,1,opt,name=AccountID" json:"AccountID,omitempty"`
	// different assets
	Assets []*Asset `protobuf:"bytes,2,rep,name=Assets" json:"Assets,omitempty"`
	// public key of the signer of this account
	Signer string `protobuf:"bytes,3,opt,name=Signer" json:"Signer,omitempty"`
	// latest transaction sequence number
	SequenceNumber uint64 `protobuf:"varint,4,opt,name=SequenceNumber" json:"SequenceNumber,omitempty"`
	// hashes of transactions belongs to this account
	TxHashList []string `protobuf:"bytes,5,rep,name=TxHashList" json:"TxHashList,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Account) GetAssets() []*Asset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *Account) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *Account) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Account) GetTxHashList() []string {
	if m != nil {
		return m.TxHashList
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "ultpb.Account")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xcd, 0x29, 0x29, 0x48,
	0x92, 0xe2, 0x4e, 0x2c, 0x2e, 0x4e, 0x85, 0x8a, 0x29, 0xad, 0x65, 0xe4, 0x62, 0x77, 0x84, 0xa8,
	0x12, 0x92, 0xe1, 0xe2, 0x84, 0x32, 0x3d, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10,
	0x02, 0x42, 0x2a, 0x5c, 0x6c, 0x8e, 0x20, 0x8d, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46,
	0x3c, 0x7a, 0x60, 0xe3, 0xf4, 0xc0, 0x82, 0x41, 0x50, 0x39, 0x21, 0x31, 0x2e, 0xb6, 0xe0, 0xcc,
	0xf4, 0xbc, 0xd4, 0x22, 0x09, 0x66, 0xb0, 0x01, 0x50, 0x9e, 0x90, 0x1a, 0x17, 0x5f, 0x70, 0x6a,
	0x61, 0x69, 0x6a, 0x5e, 0x72, 0xaa, 0x5f, 0x69, 0x6e, 0x52, 0x6a, 0x91, 0x04, 0x8b, 0x02, 0xa3,
	0x06, 0x4b, 0x10, 0x9a, 0xa8, 0x90, 0x1c, 0x17, 0x57, 0x48, 0x85, 0x47, 0x62, 0x71, 0x86, 0x4f,
	0x66, 0x71, 0x89, 0x04, 0xab, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x92, 0x48, 0x12, 0x1b, 0xd8, 0xd9,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0xa0, 0x03, 0x54, 0xdb, 0x00, 0x00, 0x00,
}
