// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consensus.proto

package ultpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Statement is an abstractive value for nodes to vote
// and reach consensus. Each statement type has its
// corresponding data encoded in pb and saved in Data field.
type StatementType int32

const (
	StatementType_NOMINATE    StatementType = 0
	StatementType_PREPARE     StatementType = 1
	StatementType_CONFIRM     StatementType = 2
	StatementType_EXTERNALIZE StatementType = 3
)

var StatementType_name = map[int32]string{
	0: "NOMINATE",
	1: "PREPARE",
	2: "CONFIRM",
	3: "EXTERNALIZE",
}
var StatementType_value = map[string]int32{
	"NOMINATE":    0,
	"PREPARE":     1,
	"CONFIRM":     2,
	"EXTERNALIZE": 3,
}

func (x StatementType) String() string {
	return proto.EnumName(StatementType_name, int32(x))
}
func (StatementType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

// ConsensusValue is used for reaching consensus in
// Federated Byzantine Agreement
type ConsensusValue struct {
	// hash of the transaction list
	TxListHash string `protobuf:"bytes,1,opt,name=TxListHash" json:"TxListHash,omitempty"`
	// propose time
	ProposeTime int64 `protobuf:"varint,2,opt,name=ProposeTime" json:"ProposeTime,omitempty"`
	// close time
	CloseTime int64 `protobuf:"varint,3,opt,name=CloseTime" json:"CloseTime,omitempty"`
}

func (m *ConsensusValue) Reset()                    { *m = ConsensusValue{} }
func (m *ConsensusValue) String() string            { return proto.CompactTextString(m) }
func (*ConsensusValue) ProtoMessage()               {}
func (*ConsensusValue) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ConsensusValue) GetTxListHash() string {
	if m != nil {
		return m.TxListHash
	}
	return ""
}

func (m *ConsensusValue) GetProposeTime() int64 {
	if m != nil {
		return m.ProposeTime
	}
	return 0
}

func (m *ConsensusValue) GetCloseTime() int64 {
	if m != nil {
		return m.CloseTime
	}
	return 0
}

// Each ULTNode is associated with a quorum, every message
// related to FBA consensus should contain the quorum of
// the node
type Quorum struct {
	Threshold   float64   `protobuf:"fixed64,1,opt,name=Threshold" json:"Threshold,omitempty"`
	Validators  []string  `protobuf:"bytes,2,rep,name=Validators" json:"Validators,omitempty"`
	NestQuorums []*Quorum `protobuf:"bytes,3,rep,name=NestQuorums" json:"NestQuorums,omitempty"`
}

func (m *Quorum) Reset()                    { *m = Quorum{} }
func (m *Quorum) String() string            { return proto.CompactTextString(m) }
func (*Quorum) ProtoMessage()               {}
func (*Quorum) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Quorum) GetThreshold() float64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *Quorum) GetValidators() []string {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *Quorum) GetNestQuorums() []*Quorum {
	if m != nil {
		return m.NestQuorums
	}
	return nil
}

// Nomination is used to find a candidate value for
// later federated voting of ballot
type Nomination struct {
	VoteList   []string `protobuf:"bytes,1,rep,name=VoteList" json:"VoteList,omitempty"`
	AcceptList []string `protobuf:"bytes,2,rep,name=AcceptList" json:"AcceptList,omitempty"`
	QuorumHash string   `protobuf:"bytes,3,opt,name=QuorumHash" json:"QuorumHash,omitempty"`
}

func (m *Nomination) Reset()                    { *m = Nomination{} }
func (m *Nomination) String() string            { return proto.CompactTextString(m) }
func (*Nomination) ProtoMessage()               {}
func (*Nomination) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Nomination) GetVoteList() []string {
	if m != nil {
		return m.VoteList
	}
	return nil
}

func (m *Nomination) GetAcceptList() []string {
	if m != nil {
		return m.AcceptList
	}
	return nil
}

func (m *Nomination) GetQuorumHash() string {
	if m != nil {
		return m.QuorumHash
	}
	return ""
}

// Ballot is used to finalize a consensus value for
// a specific decree
type Ballot struct {
	// ballot counter
	Counter uint64 `protobuf:"varint,1,opt,name=Counter" json:"Counter,omitempty"`
	// composite candidate value
	Value string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *Ballot) Reset()                    { *m = Ballot{} }
func (m *Ballot) String() string            { return proto.CompactTextString(m) }
func (*Ballot) ProtoMessage()               {}
func (*Ballot) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *Ballot) GetCounter() uint64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func (m *Ballot) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Statement struct {
	StatementType StatementType `protobuf:"varint,1,opt,name=StatementType,enum=ultpb.StatementType" json:"StatementType,omitempty"`
	// node ID of sender
	NodeID string `protobuf:"bytes,2,opt,name=NodeID" json:"NodeID,omitempty"`
	// decree index
	Index uint64 `protobuf:"varint,3,opt,name=Index" json:"Index,omitempty"`
	// nomination or ballot in pb format
	Data []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *Statement) Reset()                    { *m = Statement{} }
func (m *Statement) String() string            { return proto.CompactTextString(m) }
func (*Statement) ProtoMessage()               {}
func (*Statement) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *Statement) GetStatementType() StatementType {
	if m != nil {
		return m.StatementType
	}
	return StatementType_NOMINATE
}

func (m *Statement) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *Statement) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Statement) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ConsensusValue)(nil), "ultpb.ConsensusValue")
	proto.RegisterType((*Quorum)(nil), "ultpb.Quorum")
	proto.RegisterType((*Nomination)(nil), "ultpb.Nomination")
	proto.RegisterType((*Ballot)(nil), "ultpb.Ballot")
	proto.RegisterType((*Statement)(nil), "ultpb.Statement")
	proto.RegisterEnum("ultpb.StatementType", StatementType_name, StatementType_value)
}

func init() { proto.RegisterFile("consensus.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x5f, 0x8b, 0x9b, 0x40,
	0x14, 0xc5, 0x3b, 0xd1, 0x75, 0xd7, 0xeb, 0xfe, 0x91, 0x61, 0x29, 0x52, 0x4a, 0x11, 0x9f, 0xa4,
	0x0f, 0x29, 0x6c, 0x5f, 0x4a, 0xdf, 0xac, 0x6b, 0x59, 0x61, 0xd7, 0xa4, 0x53, 0x09, 0xa5, 0x6f,
	0x93, 0x38, 0xa0, 0xa0, 0x8e, 0x38, 0x23, 0x4d, 0x3f, 0x42, 0xbf, 0x75, 0x99, 0xd1, 0xc4, 0x64,
	0xdf, 0xe6, 0xfc, 0xce, 0xe5, 0x9e, 0x7b, 0x2f, 0x03, 0x77, 0x3b, 0xde, 0x0a, 0xd6, 0x8a, 0x41,
	0x2c, 0xbb, 0x9e, 0x4b, 0x8e, 0x2f, 0x86, 0x5a, 0x76, 0xdb, 0xa0, 0x83, 0xdb, 0xf8, 0xe0, 0x6c,
	0x68, 0x3d, 0x30, 0xfc, 0x01, 0x20, 0xdf, 0x3f, 0x57, 0x42, 0x3e, 0x51, 0x51, 0x7a, 0xc8, 0x47,
	0xa1, 0x4d, 0x4e, 0x08, 0xf6, 0xc1, 0x59, 0xf7, 0xbc, 0xe3, 0x82, 0xe5, 0x55, 0xc3, 0xbc, 0x85,
	0x8f, 0x42, 0x83, 0x9c, 0x22, 0xfc, 0x1e, 0xec, 0xb8, 0x3e, 0xf8, 0x86, 0xf6, 0x67, 0x10, 0xfc,
	0x01, 0xeb, 0xc7, 0xc0, 0xfb, 0xa1, 0x51, 0x75, 0x79, 0xd9, 0x33, 0x51, 0xf2, 0xba, 0xd0, 0x41,
	0x88, 0xcc, 0x40, 0xcd, 0xb1, 0xa1, 0x75, 0x55, 0x50, 0xc9, 0x7b, 0xe1, 0x2d, 0x7c, 0x43, 0xcd,
	0x31, 0x13, 0xfc, 0x09, 0x9c, 0x8c, 0x09, 0x39, 0xf6, 0x12, 0x9e, 0xe1, 0x1b, 0xa1, 0xf3, 0x70,
	0xb3, 0xd4, 0x6b, 0x2d, 0x47, 0x4a, 0x4e, 0x2b, 0x82, 0x12, 0x20, 0xe3, 0x4d, 0xd5, 0x52, 0x59,
	0xf1, 0x16, 0xbf, 0x83, 0xab, 0x0d, 0x97, 0x4c, 0xad, 0xe5, 0x21, 0xdd, 0xfc, 0xa8, 0x55, 0x74,
	0xb4, 0xdb, 0xb1, 0x4e, 0x6a, 0x77, 0x8a, 0x9e, 0x89, 0xf2, 0xc7, 0xa6, 0xfa, 0x44, 0xc6, 0x78,
	0xa2, 0x99, 0x04, 0x5f, 0xc0, 0xfa, 0x46, 0xeb, 0x9a, 0x4b, 0xec, 0xc1, 0x65, 0xcc, 0x87, 0x56,
	0xb2, 0x5e, 0x2f, 0x68, 0x92, 0x83, 0xc4, 0xf7, 0x70, 0xa1, 0xef, 0xad, 0x0f, 0x68, 0x93, 0x51,
	0x04, 0xff, 0x10, 0xd8, 0x3f, 0x25, 0x95, 0xac, 0x61, 0xad, 0xc4, 0x5f, 0xe1, 0xe6, 0x28, 0xf2,
	0xbf, 0x1d, 0xd3, 0x3d, 0x6e, 0x1f, 0xee, 0xa7, 0x25, 0xcf, 0x3c, 0x72, 0x5e, 0x8a, 0xdf, 0x82,
	0x95, 0xf1, 0x82, 0xa5, 0x8f, 0x53, 0xc0, 0xa4, 0x54, 0x6e, 0xda, 0x16, 0x6c, 0xaf, 0xc7, 0x36,
	0xc9, 0x28, 0x30, 0x06, 0xf3, 0x91, 0x4a, 0xea, 0x99, 0x3e, 0x0a, 0xaf, 0x89, 0x7e, 0x7f, 0x7c,
	0x7a, 0x95, 0x8e, 0xaf, 0xe1, 0x2a, 0x5b, 0xbd, 0xa4, 0x59, 0x94, 0x27, 0xee, 0x1b, 0xec, 0xc0,
	0xe5, 0x9a, 0x24, 0xeb, 0x88, 0x24, 0x2e, 0x52, 0x22, 0x5e, 0x65, 0xdf, 0x53, 0xf2, 0xe2, 0x2e,
	0xf0, 0x1d, 0x38, 0xc9, 0xaf, 0x3c, 0x21, 0x59, 0xf4, 0x9c, 0xfe, 0x4e, 0x5c, 0x63, 0x6b, 0xe9,
	0x2f, 0xf7, 0xf9, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x01, 0xb7, 0x11, 0x85, 0x02, 0x00,
	0x00,
}
