// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger.proto

/*
Package ultpb is a generated protocol buffer package.

It is generated from these files:
	ledger.proto

It has these top-level messages:
	LedgerHeader
*/
package ultpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LedgerHeader struct {
	// version of pb message, each time we update the pb message definition, the
	// version number will incremented. The specific version number to use is
	// hard coded and changed each time we do some changes.
	Version uint32 `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	// hash of the previous ledger
	PrevLedgerHash string `protobuf:"bytes,2,opt,name=PrevLedgerHash" json:"PrevLedgerHash,omitempty"`
	// hash of the transaction list in this ledger
	TxListHash string `protobuf:"bytes,3,opt,name=TxListHash" json:"TxListHash,omitempty"`
	// the consensus value the network agreed in hex coding string
	ConsensusValue string `protobuf:"bytes,4,opt,name=ConsensusValue" json:"ConsensusValue,omitempty"`
	// maximun number of transactions allowed in a transaction list
	MaxTxListSize uint32 `protobuf:"varint,5,opt,name=MaxTxListSize" json:"MaxTxListSize,omitempty"`
	// sequence number of this ledger
	SeqNum uint64 `protobuf:"varint,6,opt,name=SeqNum" json:"SeqNum,omitempty"`
	// total number of tokens in existence
	TotalTokens uint64 `protobuf:"varint,7,opt,name=TotalTokens" json:"TotalTokens,omitempty"`
	// base fee per operation
	BaseFee uint64 `protobuf:"varint,8,opt,name=BaseFee" json:"BaseFee,omitempty"`
	// base reserver for an account
	BaseReserve uint64 `protobuf:"varint,9,opt,name=BaseReserve" json:"BaseReserve,omitempty"`
	// close time
	CloseTime int64 `protobuf:"varint,10,opt,name=CloseTime" json:"CloseTime,omitempty"`
}

func (m *LedgerHeader) Reset()                    { *m = LedgerHeader{} }
func (m *LedgerHeader) String() string            { return proto.CompactTextString(m) }
func (*LedgerHeader) ProtoMessage()               {}
func (*LedgerHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LedgerHeader) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *LedgerHeader) GetPrevLedgerHash() string {
	if m != nil {
		return m.PrevLedgerHash
	}
	return ""
}

func (m *LedgerHeader) GetTxListHash() string {
	if m != nil {
		return m.TxListHash
	}
	return ""
}

func (m *LedgerHeader) GetConsensusValue() string {
	if m != nil {
		return m.ConsensusValue
	}
	return ""
}

func (m *LedgerHeader) GetMaxTxListSize() uint32 {
	if m != nil {
		return m.MaxTxListSize
	}
	return 0
}

func (m *LedgerHeader) GetSeqNum() uint64 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *LedgerHeader) GetTotalTokens() uint64 {
	if m != nil {
		return m.TotalTokens
	}
	return 0
}

func (m *LedgerHeader) GetBaseFee() uint64 {
	if m != nil {
		return m.BaseFee
	}
	return 0
}

func (m *LedgerHeader) GetBaseReserve() uint64 {
	if m != nil {
		return m.BaseReserve
	}
	return 0
}

func (m *LedgerHeader) GetCloseTime() int64 {
	if m != nil {
		return m.CloseTime
	}
	return 0
}

func init() {
	proto.RegisterType((*LedgerHeader)(nil), "ultpb.LedgerHeader")
}

func init() { proto.RegisterFile("ledger.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x99, 0xfe, 0x3a, 0xd7, 0xd6, 0x45, 0x16, 0x72, 0x17, 0x22, 0x41, 0x44, 0x66, 0xe5,
	0xc6, 0x37, 0xb0, 0x20, 0x2e, 0xaa, 0x48, 0x3a, 0x74, 0x9f, 0xd2, 0x83, 0x0e, 0xa6, 0x93, 0x9a,
	0x3b, 0x53, 0x8a, 0x8f, 0xe9, 0x13, 0xc9, 0x64, 0x5a, 0x9c, 0xba, 0xcb, 0xf9, 0xce, 0x0f, 0x49,
	0x68, 0xe2, 0xb0, 0x7e, 0x47, 0xb8, 0xdf, 0x06, 0x5f, 0x79, 0x35, 0xac, 0x5d, 0xb5, 0x5d, 0xdd,
	0xfc, 0xf4, 0x68, 0x32, 0x8f, 0xfc, 0x19, 0x76, 0x8d, 0xa0, 0x98, 0xc6, 0x4b, 0x04, 0x29, 0x7c,
	0xc9, 0x89, 0x4e, 0xb2, 0xa9, 0x39, 0x4a, 0x75, 0x47, 0x17, 0x6f, 0x01, 0xbb, 0x43, 0xda, 0xca,
	0x07, 0xf7, 0x74, 0x92, 0xa5, 0xe6, 0x1f, 0x55, 0xd7, 0x44, 0xf9, 0x7e, 0x5e, 0x48, 0x15, 0x33,
	0xfd, 0x98, 0xe9, 0x90, 0x66, 0x67, 0xe6, 0x4b, 0x41, 0x29, 0xb5, 0x2c, 0xad, 0xab, 0xc1, 0x83,
	0x76, 0xe7, 0x94, 0xaa, 0x5b, 0x9a, 0xbe, 0xd8, 0x7d, 0x5b, 0x5c, 0x14, 0xdf, 0xe0, 0x61, 0xbc,
	0xcf, 0x29, 0x54, 0x97, 0x34, 0x5a, 0xe0, 0xeb, 0xb5, 0xde, 0xf0, 0x48, 0x27, 0xd9, 0xc0, 0x1c,
	0x94, 0xd2, 0x74, 0x9e, 0xfb, 0xca, 0xba, 0xdc, 0x7f, 0xa2, 0x14, 0x1e, 0x47, 0xb3, 0x8b, 0x9a,
	0x97, 0x3e, 0x5a, 0xc1, 0x13, 0xc0, 0x67, 0xd1, 0x3d, 0xca, 0xa6, 0xdb, 0x1c, 0x0d, 0x04, 0x61,
	0x07, 0x4e, 0xdb, 0x6e, 0x07, 0xa9, 0x2b, 0x4a, 0x67, 0xce, 0x0b, 0xf2, 0x62, 0x03, 0x26, 0x9d,
	0x64, 0x7d, 0xf3, 0x07, 0x56, 0xa3, 0xf8, 0xc5, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc4,
	0x05, 0xc3, 0xcc, 0x72, 0x01, 0x00, 0x00,
}
