// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger.proto

package ultpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LedgerHeader struct {
	// Version of pb message, each time we update the pb message definition, the
	// version number will incremented. The specific version number to use is
	// hard coded and changed each time we do some changes.
	Version uint32 `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	// Hash of the previous ledger.
	PrevLedgerHash string `protobuf:"bytes,2,opt,name=PrevLedgerHash" json:"PrevLedgerHash,omitempty"`
	// Hash of the transaction set in this ledger.
	TxSetHash string `protobuf:"bytes,3,opt,name=TxSetHash" json:"TxSetHash,omitempty"`
	// The consensus value the network agreed in hex coding string.
	ConsensusValue string `protobuf:"bytes,4,opt,name=ConsensusValue" json:"ConsensusValue,omitempty"`
	// Maximun number of transactions allowed in a transaction list.
	MaxTxListSize uint32 `protobuf:"varint,5,opt,name=MaxTxListSize" json:"MaxTxListSize,omitempty"`
	// Sequence number of this ledger.
	SeqNum uint64 `protobuf:"varint,6,opt,name=SeqNum" json:"SeqNum,omitempty"`
	// Total number of tokens in existence.
	TotalTokens int64 `protobuf:"varint,7,opt,name=TotalTokens" json:"TotalTokens,omitempty"`
	// Base fee per operation.
	BaseFee int64 `protobuf:"varint,8,opt,name=BaseFee" json:"BaseFee,omitempty"`
	// Base reserve for an account.
	BaseReserve int64 `protobuf:"varint,9,opt,name=BaseReserve" json:"BaseReserve,omitempty"`
}

func (m *LedgerHeader) Reset()                    { *m = LedgerHeader{} }
func (m *LedgerHeader) String() string            { return proto.CompactTextString(m) }
func (*LedgerHeader) ProtoMessage()               {}
func (*LedgerHeader) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *LedgerHeader) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *LedgerHeader) GetPrevLedgerHash() string {
	if m != nil {
		return m.PrevLedgerHash
	}
	return ""
}

func (m *LedgerHeader) GetTxSetHash() string {
	if m != nil {
		return m.TxSetHash
	}
	return ""
}

func (m *LedgerHeader) GetConsensusValue() string {
	if m != nil {
		return m.ConsensusValue
	}
	return ""
}

func (m *LedgerHeader) GetMaxTxListSize() uint32 {
	if m != nil {
		return m.MaxTxListSize
	}
	return 0
}

func (m *LedgerHeader) GetSeqNum() uint64 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *LedgerHeader) GetTotalTokens() int64 {
	if m != nil {
		return m.TotalTokens
	}
	return 0
}

func (m *LedgerHeader) GetBaseFee() int64 {
	if m != nil {
		return m.BaseFee
	}
	return 0
}

func (m *LedgerHeader) GetBaseReserve() int64 {
	if m != nil {
		return m.BaseReserve
	}
	return 0
}

// Full ledger info of a ledger index.
type Ledger struct {
	LedgerHeader *LedgerHeader `protobuf:"bytes,1,opt,name=LedgerHeader" json:"LedgerHeader,omitempty"`
	TxSet        *TxSet        `protobuf:"bytes,2,opt,name=TxSet" json:"TxSet,omitempty"`
}

func (m *Ledger) Reset()                    { *m = Ledger{} }
func (m *Ledger) String() string            { return proto.CompactTextString(m) }
func (*Ledger) ProtoMessage()               {}
func (*Ledger) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *Ledger) GetLedgerHeader() *LedgerHeader {
	if m != nil {
		return m.LedgerHeader
	}
	return nil
}

func (m *Ledger) GetTxSet() *TxSet {
	if m != nil {
		return m.TxSet
	}
	return nil
}

// LedgerCheckpoint contains the states of the latest closed ledger.
// It is mainly used for making the snapshot of the states of the
// latest closed ledger so that the node can recover its states
// after node failures.
type LedgerCheckpoint struct {
	// Timestamp of last ledger closed.
	LastCloseTime int64 `protobuf:"varint,1,opt,name=LastCloseTime" json:"LastCloseTime,omitempty"`
	// The number of ledgers processed.
	LedgerHeaderCount int64 `protobuf:"varint,2,opt,name=LedgerHeaderCount" json:"LedgerHeaderCount,omitempty"`
	// The largest consensus index that the manager met.
	LargestConsensusIndex uint64 `protobuf:"varint,3,opt,name=LargestConsensusIndex" json:"LargestConsensusIndex,omitempty"`
	// Previous committed ledger header.
	PrevLedgerHeader *LedgerHeader `protobuf:"bytes,4,opt,name=PrevLedgerHeader" json:"PrevLedgerHeader,omitempty"`
	// Hash of previous committed ledger header.
	PrevLedgerHeaderHash string `protobuf:"bytes,5,opt,name=PrevLedgerHeaderHash" json:"PrevLedgerHeaderHash,omitempty"`
	// Current latest committed ledger header.
	CurrLedgerHeader *LedgerHeader `protobuf:"bytes,6,opt,name=CurrLedgerHeader" json:"CurrLedgerHeader,omitempty"`
	// Hash of current latest committed ledger header.
	CurrLedgerHeaderHash string `protobuf:"bytes,7,opt,name=CurrLedgerHeaderHash" json:"CurrLedgerHeaderHash,omitempty"`
}

func (m *LedgerCheckpoint) Reset()                    { *m = LedgerCheckpoint{} }
func (m *LedgerCheckpoint) String() string            { return proto.CompactTextString(m) }
func (*LedgerCheckpoint) ProtoMessage()               {}
func (*LedgerCheckpoint) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *LedgerCheckpoint) GetLastCloseTime() int64 {
	if m != nil {
		return m.LastCloseTime
	}
	return 0
}

func (m *LedgerCheckpoint) GetLedgerHeaderCount() int64 {
	if m != nil {
		return m.LedgerHeaderCount
	}
	return 0
}

func (m *LedgerCheckpoint) GetLargestConsensusIndex() uint64 {
	if m != nil {
		return m.LargestConsensusIndex
	}
	return 0
}

func (m *LedgerCheckpoint) GetPrevLedgerHeader() *LedgerHeader {
	if m != nil {
		return m.PrevLedgerHeader
	}
	return nil
}

func (m *LedgerCheckpoint) GetPrevLedgerHeaderHash() string {
	if m != nil {
		return m.PrevLedgerHeaderHash
	}
	return ""
}

func (m *LedgerCheckpoint) GetCurrLedgerHeader() *LedgerHeader {
	if m != nil {
		return m.CurrLedgerHeader
	}
	return nil
}

func (m *LedgerCheckpoint) GetCurrLedgerHeaderHash() string {
	if m != nil {
		return m.CurrLedgerHeaderHash
	}
	return ""
}

func init() {
	proto.RegisterType((*LedgerHeader)(nil), "ultpb.LedgerHeader")
	proto.RegisterType((*Ledger)(nil), "ultpb.Ledger")
	proto.RegisterType((*LedgerCheckpoint)(nil), "ultpb.LedgerCheckpoint")
}

func init() { proto.RegisterFile("ledger.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x25, 0x9b, 0x8f, 0xda, 0x69, 0x57, 0x76, 0xc7, 0x0f, 0x06, 0xf1, 0x21, 0x04, 0x91, 0x3c,
	0x48, 0x1f, 0xaa, 0xe0, 0xa3, 0x60, 0x40, 0x14, 0xa2, 0xc8, 0x34, 0xec, 0xfb, 0x6c, 0x7b, 0x69,
	0x43, 0xd3, 0x99, 0x3a, 0x33, 0x29, 0xc1, 0x1f, 0xe0, 0x0f, 0xf2, 0x17, 0x4a, 0xee, 0xb4, 0x9a,
	0xa4, 0x75, 0xdf, 0x72, 0xcf, 0x39, 0x77, 0x4e, 0xee, 0xb9, 0x33, 0x64, 0x5a, 0xc1, 0x6a, 0x0d,
	0x7a, 0xb6, 0xd7, 0xca, 0x2a, 0x1a, 0xd6, 0x95, 0xdd, 0xdf, 0xbf, 0xb8, 0xb5, 0x5a, 0x48, 0x23,
	0x96, 0xb6, 0x54, 0xd2, 0x31, 0xc9, 0xef, 0x2b, 0x32, 0xcd, 0x51, 0xfa, 0x19, 0xc4, 0x0a, 0x34,
	0x65, 0x64, 0x74, 0x07, 0xda, 0x94, 0x4a, 0x32, 0x2f, 0xf6, 0xd2, 0x6b, 0x7e, 0x2a, 0xe9, 0x6b,
	0xf2, 0xf8, 0xbb, 0x86, 0xc3, 0x51, 0x2d, 0xcc, 0x86, 0x5d, 0xc5, 0x5e, 0x3a, 0xe6, 0x03, 0x94,
	0xbe, 0x24, 0xe3, 0xa2, 0x59, 0x80, 0x45, 0x89, 0x8f, 0x92, 0x7f, 0x40, 0x7b, 0x4a, 0xa6, 0xa4,
	0x01, 0x69, 0x6a, 0x73, 0x27, 0xaa, 0x1a, 0x58, 0xe0, 0x4e, 0xe9, 0xa3, 0xf4, 0x15, 0xb9, 0xfe,
	0x2a, 0x9a, 0xa2, 0xc9, 0x4b, 0x63, 0x17, 0xe5, 0x4f, 0x60, 0x21, 0xfe, 0x4d, 0x1f, 0xa4, 0xcf,
	0x49, 0xb4, 0x80, 0x1f, 0xdf, 0xea, 0x1d, 0x8b, 0x62, 0x2f, 0x0d, 0xf8, 0xb1, 0xa2, 0x31, 0x99,
	0x14, 0xca, 0x8a, 0xaa, 0x50, 0x5b, 0x90, 0x86, 0x8d, 0x62, 0x2f, 0xf5, 0x79, 0x17, 0x6a, 0xe7,
	0xfc, 0x28, 0x0c, 0x7c, 0x02, 0x60, 0x8f, 0x90, 0x3d, 0x95, 0x6d, 0x6f, 0xfb, 0xc9, 0xc1, 0x80,
	0x3e, 0x00, 0x1b, 0xbb, 0xde, 0x0e, 0x94, 0x00, 0x89, 0xdc, 0xbc, 0xf4, 0x7d, 0x3f, 0x3d, 0x8c,
	0x6c, 0x32, 0x7f, 0x32, 0xc3, 0xbc, 0x67, 0x5d, 0x8a, 0xf7, 0x63, 0x4e, 0x48, 0x88, 0x99, 0x60,
	0x86, 0x93, 0xf9, 0xf4, 0xd8, 0x81, 0x18, 0x77, 0x54, 0xf2, 0xcb, 0x27, 0x37, 0xae, 0x29, 0xdb,
	0xc0, 0x72, 0xbb, 0x57, 0xa5, 0xb4, 0x6d, 0x2e, 0xb9, 0x30, 0x36, 0xab, 0x94, 0x81, 0xa2, 0xdc,
	0x01, 0x5a, 0xfa, 0xbc, 0x0f, 0xd2, 0x37, 0xe4, 0xb6, 0x6b, 0x97, 0xa9, 0x5a, 0x3a, 0x2b, 0x9f,
	0x9f, 0x13, 0xf4, 0x1d, 0x79, 0x96, 0x0b, 0xbd, 0x06, 0x63, 0xff, 0x2e, 0xe1, 0x8b, 0x5c, 0x41,
	0x83, 0xdb, 0x0b, 0xf8, 0x65, 0x92, 0x7e, 0x20, 0x37, 0x9d, 0xcd, 0xbb, 0xf9, 0x83, 0xff, 0xcf,
	0x7f, 0x26, 0xa6, 0x73, 0xf2, 0x74, 0x88, 0xe1, 0x9d, 0x09, 0xf1, 0x42, 0x5c, 0xe4, 0x5a, 0xd3,
	0xac, 0xd6, 0xba, 0x67, 0x1a, 0x3d, 0x60, 0x3a, 0x14, 0xb7, 0xa6, 0x43, 0x0c, 0x4d, 0x47, 0xce,
	0xf4, 0x12, 0x77, 0x1f, 0xe1, 0x5b, 0x79, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0x57, 0x3e, 0x25,
	0x8c, 0x55, 0x03, 0x00, 0x00,
}
