// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package ultpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// every operation is related to a specific account and
// each transaction could contain one or more operations
type OpTypeEnum int32

const (
	OpTypeEnum_CREATE_ACCOUNT OpTypeEnum = 0
	OpTypeEnum_PAYMENT        OpTypeEnum = 1
)

var OpTypeEnum_name = map[int32]string{
	0: "CREATE_ACCOUNT",
	1: "PAYMENT",
}
var OpTypeEnum_value = map[string]int32{
	"CREATE_ACCOUNT": 0,
	"PAYMENT":        1,
}

func (x OpTypeEnum) String() string {
	return proto.EnumName(OpTypeEnum_name, int32(x))
}
func (OpTypeEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

// operation
type Op struct {
	// operation type of this transaction
	OpType OpTypeEnum `protobuf:"varint,1,opt,name=OpType,enum=ultpb.OpTypeEnum" json:"OpType,omitempty"`
	// operation details in wire format
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *Op) Reset()                    { *m = Op{} }
func (m *Op) String() string            { return proto.CompactTextString(m) }
func (*Op) ProtoMessage()               {}
func (*Op) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Op) GetOpType() OpTypeEnum {
	if m != nil {
		return m.OpType
	}
	return OpTypeEnum_CREATE_ACCOUNT
}

func (m *Op) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// transaction
type Tx struct {
	// the source account for sending asset to the new account
	AccountID string `protobuf:"bytes,1,opt,name=AccountID" json:"AccountID,omitempty"`
	// fee to pay
	Fee uint64 `protobuf:"varint,2,opt,name=Fee" json:"Fee,omitempty"`
	// extra note about the transaction
	Note string `protobuf:"bytes,3,opt,name=Note" json:"Note,omitempty"`
	// unique transaction sequence number
	SequenceNumber uint64 `protobuf:"varint,4,opt,name=SequenceNumber" json:"SequenceNumber,omitempty"`
	// list of operations
	OpList []*Op `protobuf:"bytes,5,rep,name=OpList" json:"OpList,omitempty"`
}

func (m *Tx) Reset()                    { *m = Tx{} }
func (m *Tx) String() string            { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()               {}
func (*Tx) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *Tx) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Tx) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Tx) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Tx) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *Tx) GetOpList() []*Op {
	if m != nil {
		return m.OpList
	}
	return nil
}

type TxList struct {
	// hash of previous closed ledger header
	PrevLedgerHash string `protobuf:"bytes,1,opt,name=PrevLedgerHash" json:"PrevLedgerHash,omitempty"`
	// list of transactions
	Txs []*Tx `protobuf:"bytes,2,rep,name=Txs" json:"Txs,omitempty"`
}

func (m *TxList) Reset()                    { *m = TxList{} }
func (m *TxList) String() string            { return proto.CompactTextString(m) }
func (*TxList) ProtoMessage()               {}
func (*TxList) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *TxList) GetPrevLedgerHash() string {
	if m != nil {
		return m.PrevLedgerHash
	}
	return ""
}

func (m *TxList) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

// create a new account by sending asset to it
type CreateAccountOp struct {
	// destination account
	AccountID string `protobuf:"bytes,1,opt,name=AccountID" json:"AccountID,omitempty"`
	// the initial asset and balance
	AssetType Asset_AssetTypeEnum `protobuf:"varint,2,opt,name=AssetType,enum=ultpb.Asset_AssetTypeEnum" json:"AssetType,omitempty"`
	Balance   int64               `protobuf:"varint,3,opt,name=Balance" json:"Balance,omitempty"`
}

func (m *CreateAccountOp) Reset()                    { *m = CreateAccountOp{} }
func (m *CreateAccountOp) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountOp) ProtoMessage()               {}
func (*CreateAccountOp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *CreateAccountOp) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CreateAccountOp) GetAssetType() Asset_AssetTypeEnum {
	if m != nil {
		return m.AssetType
	}
	return Asset_NATIVE
}

func (m *CreateAccountOp) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

// peer to peer payment
type PaymentOp struct {
	// destination account of the payment
	AccountID string `protobuf:"bytes,1,opt,name=AccountID" json:"AccountID,omitempty"`
	// asset type of payment
	AssetType Asset_AssetTypeEnum `protobuf:"varint,2,opt,name=AssetType,enum=ultpb.Asset_AssetTypeEnum" json:"AssetType,omitempty"`
	// amount of payment in specified asset type
	Amount int64 `protobuf:"varint,3,opt,name=Amount" json:"Amount,omitempty"`
}

func (m *PaymentOp) Reset()                    { *m = PaymentOp{} }
func (m *PaymentOp) String() string            { return proto.CompactTextString(m) }
func (*PaymentOp) ProtoMessage()               {}
func (*PaymentOp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *PaymentOp) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *PaymentOp) GetAssetType() Asset_AssetTypeEnum {
	if m != nil {
		return m.AssetType
	}
	return Asset_NATIVE
}

func (m *PaymentOp) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*Op)(nil), "ultpb.Op")
	proto.RegisterType((*Tx)(nil), "ultpb.Tx")
	proto.RegisterType((*TxList)(nil), "ultpb.TxList")
	proto.RegisterType((*CreateAccountOp)(nil), "ultpb.CreateAccountOp")
	proto.RegisterType((*PaymentOp)(nil), "ultpb.PaymentOp")
	proto.RegisterEnum("ultpb.OpTypeEnum", OpTypeEnum_name, OpTypeEnum_value)
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x3d, 0x4f, 0xe3, 0x40,
	0x10, 0x3d, 0xdb, 0x89, 0x23, 0x4f, 0x4e, 0xb9, 0x64, 0x8b, 0x93, 0x95, 0xbb, 0x22, 0xe7, 0xe2,
	0x14, 0x90, 0x70, 0x11, 0x1a, 0x5a, 0xe3, 0x18, 0x81, 0x94, 0xd8, 0xd1, 0xb2, 0x14, 0x54, 0x68,
	0x63, 0x46, 0x10, 0x29, 0xfe, 0xc0, 0x5e, 0x23, 0x47, 0x94, 0xfc, 0x04, 0xfe, 0x30, 0xda, 0x8d,
	0x49, 0x44, 0x1a, 0x2a, 0xba, 0xb7, 0x6f, 0xdf, 0xbc, 0x99, 0x79, 0x1a, 0x18, 0x88, 0x82, 0xa7,
	0x25, 0x8f, 0xc5, 0x2a, 0x4b, 0xdd, 0xbc, 0xc8, 0x44, 0x46, 0xda, 0xd5, 0x5a, 0xe4, 0xcb, 0x61,
	0x97, 0x97, 0x25, 0x8a, 0x2d, 0xe7, 0xf8, 0xa0, 0x47, 0x39, 0x39, 0x02, 0x33, 0xca, 0xd9, 0x26,
	0x47, 0x5b, 0x1b, 0x69, 0xe3, 0xde, 0x64, 0xe0, 0x2a, 0xa9, 0xbb, 0x25, 0x83, 0xb4, 0x4a, 0x68,
	0x23, 0x20, 0x04, 0x5a, 0x53, 0x2e, 0xb8, 0xad, 0x8f, 0xb4, 0xf1, 0x4f, 0xaa, 0xb0, 0xf3, 0xa6,
	0x81, 0xce, 0x6a, 0xf2, 0x17, 0x2c, 0x2f, 0x8e, 0xb3, 0x2a, 0x15, 0x57, 0x53, 0x65, 0x64, 0xd1,
	0x3d, 0x41, 0xfa, 0x60, 0x5c, 0x20, 0xaa, 0xba, 0x16, 0x95, 0x50, 0x5a, 0x85, 0x99, 0x40, 0xdb,
	0x50, 0x52, 0x85, 0xc9, 0x7f, 0xe8, 0x5d, 0xe3, 0x53, 0x85, 0x69, 0x8c, 0x61, 0x95, 0x2c, 0xb1,
	0xb0, 0x5b, 0xaa, 0xe0, 0x80, 0x25, 0xff, 0xe4, 0xc4, 0xb3, 0x55, 0x29, 0xec, 0xf6, 0xc8, 0x18,
	0x77, 0x27, 0xd6, 0x6e, 0x62, 0xda, 0x7c, 0x38, 0x73, 0x30, 0x59, 0x2d, 0x91, 0x34, 0x5d, 0x14,
	0xf8, 0x3c, 0xc3, 0xfb, 0x07, 0x2c, 0x2e, 0x79, 0xf9, 0xd8, 0x4c, 0x77, 0xc0, 0x92, 0x3f, 0x60,
	0xb0, 0xba, 0xb4, 0xf5, 0x4f, 0x8e, 0xac, 0xa6, 0x92, 0x75, 0x5e, 0x35, 0xf8, 0xe5, 0x17, 0xc8,
	0x05, 0x36, 0x3b, 0x45, 0xf9, 0x17, 0x1b, 0x9f, 0x81, 0xe5, 0xc9, 0xa8, 0x55, 0xb0, 0xba, 0x0a,
	0x76, 0xd8, 0x98, 0x2a, 0xde, 0xdd, 0xfd, 0xaa, 0x84, 0xf7, 0x62, 0x62, 0x43, 0xe7, 0x9c, 0xaf,
	0x79, 0x1a, 0x6f, 0xc3, 0x31, 0xe8, 0xc7, 0xd3, 0x79, 0x01, 0x6b, 0xc1, 0x37, 0x09, 0x7e, 0x6b,
	0xfb, 0xdf, 0x60, 0x7a, 0x89, 0x74, 0x69, 0xba, 0x37, 0xaf, 0xe3, 0x13, 0x80, 0xfd, 0x45, 0x10,
	0x02, 0x3d, 0x9f, 0x06, 0x1e, 0x0b, 0xee, 0x3c, 0xdf, 0x8f, 0x6e, 0x42, 0xd6, 0xff, 0x41, 0xba,
	0xd0, 0x59, 0x78, 0xb7, 0xf3, 0x20, 0x64, 0x7d, 0x6d, 0x69, 0xaa, 0x13, 0x3b, 0x7d, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0x43, 0x48, 0x3a, 0x5c, 0x8b, 0x02, 0x00, 0x00,
}
