// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package ultpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// every operation is related to a specific account and
// each transaction could contain one or more operations
type OpTypeEnum int32

const (
	OpTypeEnum_CREATE_ACCOUNT OpTypeEnum = 0
	OpTypeEnum_PAYMENT        OpTypeEnum = 1
)

var OpTypeEnum_name = map[int32]string{
	0: "CREATE_ACCOUNT",
	1: "PAYMENT",
}
var OpTypeEnum_value = map[string]int32{
	"CREATE_ACCOUNT": 0,
	"PAYMENT":        1,
}

func (x OpTypeEnum) String() string {
	return proto.EnumName(OpTypeEnum_name, int32(x))
}
func (OpTypeEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

// operation
type Op struct {
	// operation type of this transaction
	OpType OpTypeEnum `protobuf:"varint,1,opt,name=OpType,enum=ultpb.OpTypeEnum" json:"OpType,omitempty"`
	// operation details in wire format
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *Op) Reset()                    { *m = Op{} }
func (m *Op) String() string            { return proto.CompactTextString(m) }
func (*Op) ProtoMessage()               {}
func (*Op) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Op) GetOpType() OpTypeEnum {
	if m != nil {
		return m.OpType
	}
	return OpTypeEnum_CREATE_ACCOUNT
}

func (m *Op) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// list of transactions
type Transaction struct {
	// the source account for sending asset to the new account
	AccountID string `protobuf:"bytes,1,opt,name=AccountID" json:"AccountID,omitempty"`
	OpList    []*Op  `protobuf:"bytes,2,rep,name=OpList" json:"OpList,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *Transaction) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Transaction) GetOpList() []*Op {
	if m != nil {
		return m.OpList
	}
	return nil
}

// create a new account by sending asset to it
type CreateAccountOp struct {
	// destination account
	AccountID string `protobuf:"bytes,1,opt,name=AccountID" json:"AccountID,omitempty"`
	// the initial asset and balance
	AssetType Asset_AssetTypeEnum `protobuf:"varint,2,opt,name=AssetType,enum=ultpb.Asset_AssetTypeEnum" json:"AssetType,omitempty"`
	Balance   int64               `protobuf:"varint,3,opt,name=Balance" json:"Balance,omitempty"`
	Signer    string              `protobuf:"bytes,4,opt,name=Signer" json:"Signer,omitempty"`
}

func (m *CreateAccountOp) Reset()                    { *m = CreateAccountOp{} }
func (m *CreateAccountOp) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountOp) ProtoMessage()               {}
func (*CreateAccountOp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *CreateAccountOp) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CreateAccountOp) GetAssetType() Asset_AssetTypeEnum {
	if m != nil {
		return m.AssetType
	}
	return Asset_NATIVE
}

func (m *CreateAccountOp) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *CreateAccountOp) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

// peer to peer payment
type PaymentOp struct {
	// destination account of the payment
	AccountID string `protobuf:"bytes,1,opt,name=AccountID" json:"AccountID,omitempty"`
	// asset type of payment
	AssetType Asset_AssetTypeEnum `protobuf:"varint,2,opt,name=AssetType,enum=ultpb.Asset_AssetTypeEnum" json:"AssetType,omitempty"`
	// amount of payment in specified asset type
	Amount int64 `protobuf:"varint,3,opt,name=Amount" json:"Amount,omitempty"`
}

func (m *PaymentOp) Reset()                    { *m = PaymentOp{} }
func (m *PaymentOp) String() string            { return proto.CompactTextString(m) }
func (*PaymentOp) ProtoMessage()               {}
func (*PaymentOp) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *PaymentOp) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *PaymentOp) GetAssetType() Asset_AssetTypeEnum {
	if m != nil {
		return m.AssetType
	}
	return Asset_NATIVE
}

func (m *PaymentOp) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*Op)(nil), "ultpb.Op")
	proto.RegisterType((*Transaction)(nil), "ultpb.Transaction")
	proto.RegisterType((*CreateAccountOp)(nil), "ultpb.CreateAccountOp")
	proto.RegisterType((*PaymentOp)(nil), "ultpb.PaymentOp")
	proto.RegisterEnum("ultpb.OpTypeEnum", OpTypeEnum_name, OpTypeEnum_value)
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x51, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0xc4, 0x69, 0x49, 0x95, 0x17, 0x54, 0x5a, 0x0f, 0x95, 0x55, 0x31, 0x84, 0x4c, 0x01, 0x89,
	0x0c, 0x65, 0x61, 0x35, 0x69, 0x06, 0x24, 0x68, 0x2a, 0x13, 0x06, 0x26, 0xe4, 0x46, 0x16, 0x8a,
	0xd4, 0x38, 0x56, 0xe2, 0x0c, 0x15, 0x9f, 0xc2, 0xcf, 0xa2, 0xb8, 0xa6, 0x19, 0x99, 0xd8, 0x7c,
	0xf7, 0xce, 0x77, 0xef, 0xf4, 0x60, 0xae, 0x1b, 0x2e, 0x5b, 0x5e, 0xe8, 0xb2, 0x96, 0xb1, 0x6a,
	0x6a, 0x5d, 0xe3, 0xf3, 0x6e, 0xaf, 0xd5, 0x6e, 0xe9, 0xf3, 0xb6, 0x15, 0xfa, 0xc8, 0x85, 0x09,
	0x38, 0x99, 0xc2, 0x37, 0xe0, 0x66, 0x2a, 0x3f, 0x28, 0x41, 0x50, 0x80, 0xa2, 0xe9, 0x6a, 0x1e,
	0x1b, 0x69, 0x7c, 0x24, 0x53, 0xd9, 0x55, 0xcc, 0x0a, 0x30, 0x86, 0xf1, 0x9a, 0x6b, 0x4e, 0x9c,
	0x00, 0x45, 0x17, 0xcc, 0xbc, 0xc3, 0x0d, 0xf8, 0xf9, 0x90, 0x86, 0xaf, 0xc0, 0xa3, 0x45, 0x51,
	0x77, 0x52, 0x3f, 0xad, 0x8d, 0xa1, 0xc7, 0x06, 0x02, 0x5f, 0xf7, 0x59, 0xcf, 0x65, 0xab, 0x89,
	0x13, 0x8c, 0x22, 0x7f, 0xe5, 0x9d, 0xb2, 0x98, 0x1d, 0x84, 0xdf, 0x08, 0x2e, 0x93, 0x46, 0x70,
	0x2d, 0xec, 0xb7, 0x4c, 0xfd, 0x61, 0xfa, 0x00, 0x1e, 0xed, 0x5b, 0x99, 0x0e, 0x8e, 0xe9, 0xb0,
	0xb4, 0xbe, 0x86, 0x8f, 0x4f, 0x53, 0x53, 0x66, 0x10, 0x63, 0x02, 0x93, 0x47, 0xbe, 0xe7, 0xb2,
	0x10, 0x64, 0x14, 0xa0, 0x68, 0xc4, 0x7e, 0x21, 0x5e, 0x80, 0xfb, 0x5a, 0x7e, 0x4a, 0xd1, 0x90,
	0xb1, 0x89, 0xb3, 0x28, 0xfc, 0x02, 0x6f, 0xcb, 0x0f, 0x95, 0xf8, 0xd7, 0xb5, 0x16, 0xe0, 0xd2,
	0xaa, 0x77, 0xb1, 0x5b, 0x59, 0x74, 0x7b, 0x07, 0x30, 0x1c, 0x05, 0x63, 0x98, 0x26, 0x2c, 0xa5,
	0x79, 0xfa, 0x41, 0x93, 0x24, 0x7b, 0xdb, 0xe4, 0xb3, 0x33, 0xec, 0xc3, 0x64, 0x4b, 0xdf, 0x5f,
	0xd2, 0x4d, 0x3e, 0x43, 0x3b, 0xd7, 0x5c, 0xf9, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x81, 0x9b,
	0x1e, 0xa2, 0x0e, 0x02, 0x00, 0x00,
}
