// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package rpcpb is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
	SubmitTxRequest
	SubmitTxResponse
	NotifyRequest
	NotifyResponse
	QueryRequest
	QueryResponse
*/
package rpcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxStatusEnum int32

const (
	TxStatusEnum_NOTEXIST  TxStatusEnum = 0
	TxStatusEnum_REJECTED  TxStatusEnum = 1
	TxStatusEnum_ACCEPTED  TxStatusEnum = 2
	TxStatusEnum_CONFIRMED TxStatusEnum = 3
	TxStatusEnum_FAILED    TxStatusEnum = 4
)

var TxStatusEnum_name = map[int32]string{
	0: "NOTEXIST",
	1: "REJECTED",
	2: "ACCEPTED",
	3: "CONFIRMED",
	4: "FAILED",
}
var TxStatusEnum_value = map[string]int32{
	"NOTEXIST":  0,
	"REJECTED":  1,
	"ACCEPTED":  2,
	"CONFIRMED": 3,
	"FAILED":    4,
}

func (x TxStatusEnum) String() string {
	return proto.EnumName(TxStatusEnum_name, int32(x))
}
func (TxStatusEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NotifyMsgType int32

const (
	NotifyMsgType_TX        NotifyMsgType = 0
	NotifyMsgType_STATEMENT NotifyMsgType = 1
)

var NotifyMsgType_name = map[int32]string{
	0: "TX",
	1: "STATEMENT",
}
var NotifyMsgType_value = map[string]int32{
	"TX":        0,
	"STATEMENT": 1,
}

func (x NotifyMsgType) String() string {
	return proto.EnumName(NotifyMsgType_name, int32(x))
}
func (NotifyMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type QueryMsgType int32

const (
	QueryMsgType_QUORUM QueryMsgType = 0
	QueryMsgType_TXSET  QueryMsgType = 1
)

var QueryMsgType_name = map[int32]string{
	0: "QUORUM",
	1: "TXSET",
}
var QueryMsgType_value = map[string]int32{
	"QUORUM": 0,
	"TXSET":  1,
}

func (x QueryMsgType) String() string {
	return proto.EnumName(QueryMsgType_name, int32(x))
}
func (QueryMsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type HelloRequest struct {
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HelloResponse struct {
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SubmitTxRequest struct {
	// transaction data in pb format
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	// transaction ULTKey
	TxKey string `protobuf:"bytes,2,opt,name=TxKey" json:"TxKey,omitempty"`
	// digital signature of the data signed by
	// the source account private key
	Signature string `protobuf:"bytes,3,opt,name=Signature" json:"Signature,omitempty"`
}

func (m *SubmitTxRequest) Reset()                    { *m = SubmitTxRequest{} }
func (m *SubmitTxRequest) String() string            { return proto.CompactTextString(m) }
func (*SubmitTxRequest) ProtoMessage()               {}
func (*SubmitTxRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SubmitTxRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SubmitTxRequest) GetTxKey() string {
	if m != nil {
		return m.TxKey
	}
	return ""
}

func (m *SubmitTxRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type SubmitTxResponse struct {
	TxStatus TxStatusEnum `protobuf:"varint,1,opt,name=TxStatus,enum=rpcpb.TxStatusEnum" json:"TxStatus,omitempty"`
	// error message for REJECTED transaction
	ErrorMessage string `protobuf:"bytes,3,opt,name=ErrorMessage" json:"ErrorMessage,omitempty"`
}

func (m *SubmitTxResponse) Reset()                    { *m = SubmitTxResponse{} }
func (m *SubmitTxResponse) String() string            { return proto.CompactTextString(m) }
func (*SubmitTxResponse) ProtoMessage()               {}
func (*SubmitTxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SubmitTxResponse) GetTxStatus() TxStatusEnum {
	if m != nil {
		return m.TxStatus
	}
	return TxStatusEnum_NOTEXIST
}

func (m *SubmitTxResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type NotifyRequest struct {
	// type of message
	MsgType NotifyMsgType `protobuf:"varint,1,opt,name=MsgType,enum=rpcpb.NotifyMsgType" json:"MsgType,omitempty"`
	// message payload in pb format
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	// digital signature of the data signed by
	// the private key of peer node
	Signature string `protobuf:"bytes,3,opt,name=Signature" json:"Signature,omitempty"`
}

func (m *NotifyRequest) Reset()                    { *m = NotifyRequest{} }
func (m *NotifyRequest) String() string            { return proto.CompactTextString(m) }
func (*NotifyRequest) ProtoMessage()               {}
func (*NotifyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NotifyRequest) GetMsgType() NotifyMsgType {
	if m != nil {
		return m.MsgType
	}
	return NotifyMsgType_TX
}

func (m *NotifyRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *NotifyRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type NotifyResponse struct {
}

func (m *NotifyResponse) Reset()                    { *m = NotifyResponse{} }
func (m *NotifyResponse) String() string            { return proto.CompactTextString(m) }
func (*NotifyResponse) ProtoMessage()               {}
func (*NotifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type QueryRequest struct {
	// type of message
	MsgType QueryMsgType `protobuf:"varint,1,opt,name=MsgType,enum=rpcpb.QueryMsgType" json:"MsgType,omitempty"`
	// message payload in pb format
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	// digital signature of the data signed by
	// the private key of peer node
	Signature string `protobuf:"bytes,3,opt,name=Signature" json:"Signature,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *QueryRequest) GetMsgType() QueryMsgType {
	if m != nil {
		return m.MsgType
	}
	return QueryMsgType_QUORUM
}

func (m *QueryRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *QueryRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type QueryResponse struct {
	// requested data encoded in pb format
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *QueryResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "rpcpb.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "rpcpb.HelloResponse")
	proto.RegisterType((*SubmitTxRequest)(nil), "rpcpb.SubmitTxRequest")
	proto.RegisterType((*SubmitTxResponse)(nil), "rpcpb.SubmitTxResponse")
	proto.RegisterType((*NotifyRequest)(nil), "rpcpb.NotifyRequest")
	proto.RegisterType((*NotifyResponse)(nil), "rpcpb.NotifyResponse")
	proto.RegisterType((*QueryRequest)(nil), "rpcpb.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "rpcpb.QueryResponse")
	proto.RegisterEnum("rpcpb.TxStatusEnum", TxStatusEnum_name, TxStatusEnum_value)
	proto.RegisterEnum("rpcpb.NotifyMsgType", NotifyMsgType_name, NotifyMsgType_value)
	proto.RegisterEnum("rpcpb.QueryMsgType", QueryMsgType_name, QueryMsgType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	SubmitTx(ctx context.Context, in *SubmitTxRequest, opts ...grpc.CallOption) (*SubmitTxResponse, error)
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/rpcpb.Node/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) SubmitTx(ctx context.Context, in *SubmitTxRequest, opts ...grpc.CallOption) (*SubmitTxResponse, error) {
	out := new(SubmitTxResponse)
	err := grpc.Invoke(ctx, "/rpcpb.Node/SubmitTx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	out := new(NotifyResponse)
	err := grpc.Invoke(ctx, "/rpcpb.Node/Notify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/rpcpb.Node/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	SubmitTx(context.Context, *SubmitTxRequest) (*SubmitTxResponse, error)
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.Node/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_SubmitTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SubmitTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.Node/SubmitTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SubmitTx(ctx, req.(*SubmitTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.Node/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.Node/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Node_Hello_Handler,
		},
		{
			MethodName: "SubmitTx",
			Handler:    _Node_SubmitTx_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _Node_Notify_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Node_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x4f, 0xba, 0x26, 0xb4, 0x4f, 0x49, 0x67, 0x3d, 0x0a, 0x54, 0x13, 0x87, 0x29, 0x08, 0x34,
	0x55, 0xa2, 0x48, 0x63, 0x12, 0x27, 0x0e, 0x55, 0xeb, 0x89, 0x02, 0x49, 0x59, 0xe2, 0x49, 0xe5,
	0x98, 0x0e, 0x53, 0x55, 0xda, 0x9a, 0x2c, 0x76, 0x50, 0xfb, 0x95, 0xf9, 0x14, 0xa8, 0xae, 0x9d,
	0x35, 0x05, 0x71, 0xda, 0x2d, 0xef, 0xf9, 0xf7, 0xfc, 0xfb, 0xe3, 0x17, 0xf0, 0x05, 0x2f, 0x7e,
	0x2d, 0x6f, 0xf8, 0x20, 0x2f, 0x32, 0x99, 0xa1, 0x53, 0xe4, 0x37, 0xf9, 0x3c, 0xe8, 0x80, 0xf7,
	0x89, 0xdf, 0xde, 0x66, 0x31, 0xbf, 0x2f, 0xb9, 0x90, 0xc1, 0x31, 0xf8, 0xba, 0x16, 0x79, 0xb6,
	0x12, 0x3c, 0xf8, 0x0e, 0xc7, 0x49, 0x39, 0xbf, 0x5b, 0x4a, 0xb6, 0xd6, 0x18, 0x44, 0x68, 0x8e,
	0x53, 0x99, 0xf6, 0xec, 0x53, 0xfb, 0xcc, 0x8b, 0xd5, 0x37, 0x76, 0xc1, 0x61, 0xeb, 0x2f, 0x7c,
	0xd3, 0x6b, 0x9c, 0xda, 0x67, 0xed, 0x78, 0x57, 0xe0, 0x4b, 0x68, 0x27, 0xcb, 0xc5, 0x2a, 0x95,
	0x65, 0xc1, 0x7b, 0x47, 0xea, 0xe4, 0xa1, 0x11, 0x2c, 0x80, 0x3c, 0x5c, 0xbd, 0xa3, 0xc3, 0x77,
	0xd0, 0x62, 0xeb, 0x44, 0xa6, 0xb2, 0x14, 0xea, 0xfe, 0xce, 0xf9, 0xd3, 0x81, 0x52, 0x3a, 0x30,
	0x6d, 0xba, 0x2a, 0xef, 0xe2, 0x0a, 0x84, 0x01, 0x78, 0xb4, 0x28, 0xb2, 0x22, 0xe4, 0x42, 0xa4,
	0x0b, 0xc3, 0x52, 0xeb, 0x05, 0xf7, 0xe0, 0x47, 0x99, 0x5c, 0xfe, 0xdc, 0x18, 0x07, 0x03, 0x78,
	0x12, 0x8a, 0x05, 0xdb, 0xe4, 0x5c, 0x93, 0x74, 0x35, 0xc9, 0x0e, 0xa6, 0xcf, 0x62, 0x03, 0xaa,
	0x1c, 0x37, 0xf6, 0x1c, 0xff, 0xdf, 0x1b, 0x81, 0x8e, 0xa1, 0xd4, 0x41, 0x66, 0xe0, 0x5d, 0x95,
	0xbc, 0xa8, 0x34, 0xbc, 0x3d, 0xd4, 0x60, 0x8c, 0x2a, 0xd4, 0x23, 0x48, 0x78, 0x05, 0xbe, 0x26,
	0xd4, 0xd9, 0xfe, 0xe3, 0xdd, 0xfa, 0x09, 0x78, 0xfb, 0xc1, 0xa2, 0x07, 0xad, 0x68, 0xca, 0xe8,
	0x6c, 0x92, 0x30, 0x62, 0x6d, 0xab, 0x98, 0x7e, 0xa6, 0x23, 0x46, 0xc7, 0xc4, 0xde, 0x56, 0xc3,
	0xd1, 0x88, 0x7e, 0xdb, 0x56, 0x0d, 0xf4, 0xa1, 0x3d, 0x9a, 0x46, 0x97, 0x93, 0x38, 0xa4, 0x63,
	0x72, 0x84, 0x00, 0xee, 0xe5, 0x70, 0xf2, 0x95, 0x8e, 0x49, 0xb3, 0xff, 0xc6, 0xe4, 0x6d, 0xc4,
	0xbb, 0xd0, 0x60, 0x33, 0x62, 0x6d, 0x67, 0x12, 0x36, 0x64, 0x34, 0xa4, 0x11, 0x23, 0x76, 0xff,
	0xb5, 0x8e, 0xc4, 0xc0, 0x00, 0xdc, 0xab, 0xeb, 0x69, 0x7c, 0x1d, 0x12, 0x0b, 0xdb, 0xe0, 0xb0,
	0x59, 0x42, 0x19, 0xb1, 0xcf, 0x7f, 0xdb, 0xd0, 0x8c, 0xb2, 0x1f, 0x1c, 0x2f, 0xc0, 0x51, 0xcb,
	0x89, 0x26, 0xaa, 0xfd, 0xd5, 0x3d, 0xe9, 0xd6, 0x9b, 0x3a, 0x76, 0x0b, 0x3f, 0x42, 0xcb, 0xac,
	0x19, 0x3e, 0xd7, 0x98, 0x83, 0x95, 0x3e, 0x79, 0xf1, 0x57, 0xbf, 0x1a, 0xff, 0x00, 0xee, 0xce,
	0x0c, 0xd6, 0x97, 0xc4, 0x8c, 0x3e, 0x3b, 0xe8, 0x56, 0x83, 0x17, 0xe0, 0x28, 0x77, 0x58, 0x7b,
	0xd8, 0x43, 0xb5, 0xb5, 0x27, 0x0a, 0xac, 0xb9, 0xab, 0x7e, 0xcf, 0xf7, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x53, 0xe8, 0x97, 0x93, 0xaf, 0x03, 0x00, 0x00,
}
